server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 47.106.210.155:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.210.155:3306/seata_account?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(BxeNcul3uiZl9lXg32vtErW5uv4l3m8y)

jasypt:
  encryptor:
    password: 1125 # 加密的salt(盐值)
    algorithm: PBEWithMD5AndDES   # 默认加密方式 PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


