server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Twroten/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
          default-label: main #读取分支
          username: Twroten
          password: ENC(pTdquxL6Me68dS5ixmn5gHt5WVBZoXCp)
          skip-ssl-validation: true

  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jasypt:
  encryptor:
    password: 1125    # 加密的salt (盐值)
    algorithm: PBEWithMD5AndDES   # 默认加密方式 PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: config-center3344
    prefer-ip-address: true

#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

