server:
  port: 7777

spring:
  application:
    name: cloud-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://47.106.210.155:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(ylB93a+j0ydZUiAwSrdO9Q==)

jasypt:
  encryptor:
    password: 1125 # 加密的salt(盐值)
    algorithm: PBEWithMD5AndDES   # 默认加密方式 PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator